### PR TITLE
Basic structure for unit test

### PR DESCRIPTION
**Pull request by rodrigosiqueira**
Signed-off-by: Pablo Alejandro <pabloabur@usp.br>
Signed-off-by: Rodrigo Siqueira <siqueira@ime.usp.br>

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
Hi,

We believe that unit test can be very healthy for yosys project because of:

1 - Having a unit test suite allows programmers to remove the fear of making changes or adding new features;
2 - It is easier for newcomers start to contribute;
3 - Tests Reduce Bugs in Existing Features.

For those reasons, we worked to add basic structure to implement unit test using google test library (gtest). We want to know if you have interest on this feature.

Ps.: You need to install lib gtest (libgtest-dev)

**Comment by cliffordwolf** [comment]
I did not have time yet to install gtest and try this. But I approve of the idea of having unit tests for the internal APIs.

I think the most obvious candidate for first unit tests would be tests for all the methods of RTLIL::SigSpec. I'd start with that, not with the logging framework.

**Comment by rodrigosiqueira** [comment]
Glad to know that you approve the idea.
We chose logging framework to start, because it looks easier for us to start working with yosys code. However, we can change to RTLIL::SigSpec or work in both of them (me and Pablo).

Finally, the purpose of this MR is to create the basic structure to add unit tests. By this regard, we can finish this basic structure (after your feedback) and then focus on the implementation of unit test for RTLIL::SigSpec. What do you think about that?

**Comment by rodrigosiqueira** [comment]
We closed this PR, because this implementation is naive and incomplete. After we interacted with other users in the Yosys Freenode and after cliffordwolf feedback, we decided to re-implement it in a better way.

**Pull request closed without merging**
