### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by gaomy3832**
One bug fix to add blackbox modules into the known celltype in opt_clean to avoid delete them.

And another minor bug fix for USE_CELL_HASH_CACHE option.

### CODE REVIEW

**Comment by cliffordwolf** [comment]
Can you give an example of the problem fixed by the "Avoid deleting blackbox modules in opt_clean." commit?

**Comment by cliffordwolf** [comment]
Btw: I did now merge the "Bugfix for cell hash cache option in opt_share." commit (8c4c62f3e1f6d0e6128c4b88f764cc58a744aee8).

**Comment by gaomy3832** [comment]
I am sorry that the commit message was incorrect. It was a bugfix some time ago when I was busy doing a project. I don't have time to submit it until recent. So I didn't remember the intention clearly.

The commit was actually indent to be able to remove unused blackbox modules, rather than keeping them. Consider the following case:
```
// foo.v
// a blackbox
module foo(a, b, y);
input a, b;
output y;
endmodule

// bar.v
// top design
module bar(a, b, y);
input a, b;
output y;
wire t;
// i0 is good
foo i0(.a(a), .b(b), .y(y));
// i1 is unused and should be removed by opt_clean
foo i1(.a(a), .b(b), .y(t));
endmodule
```

The previous version could not remove the unused module i1. Run commands
```
read_verilog -lib foo.v
read_verilog bar.v
hierarchy -check -top bar;
proc; opt; flatten; opt;
opt -full -purge;
stat
```
gives
```
=== design hierarchy ===

   bar                               1

   Number of wires:                  4
   Number of wire bits:              4
   Number of public wires:           4
   Number of public wire bits:       4
   Number of memories:               0
   Number of memory bits:            0
   Number of processes:              0
   Number of cells:                  2
     foo                             2
```

This commit fixes the problem.
```
=== design hierarchy ===

   bar                               1

   Number of wires:                  3
   Number of wire bits:              3
   Number of public wires:           3
   Number of public wire bits:       3
   Number of memories:               0
   Number of memory bits:            0
   Number of processes:              0
   Number of cells:                  1
     foo                             1
```

I've changed the commit message to reflect the correct intention.

**Comment by cliffordwolf** [comment]
Ah, ok. Yes. This makes much more sense..

**Pull request merged**
